services:
  postgres:
    image: postgres:latest
    volumes:
      - ./db_init_clean.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: arch
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: arch
      DB_PASS: postgres
      DB_NAME: database
      JWT_SECRET: secret
    restart: always
  
    
